// <auto-generated />
namespace EFEntityTypeConfigurationBlogPost.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ExtendUserEntityConfigurationWithMap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExtendUserEntityConfigurationWithMap));
        
        string IMigrationMetadata.Id
        {
            get { return "201412231321319_ExtendUserEntityConfigurationWithMap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
